language: python
python:
- '3.6'
install:
- pip install .
script:
- python setup.py bdist_wheel sdist
deploy:
  provider: pypi
  #server: https://test.pypi.org/legacy/
  user: __token__
  password:
    secure: QRnXbQgvbnBrJGe/GgEcaCjlmThYEWE3Wv+zLI4i05MqlBjCM8XOveGG5FaECGeCip2sad0IWMICq9AO3Q1kV6C2l4jCCTTi4RRJTx7NiXOzQw9u7MHLt/BRd/wwb9Spm9vd9pL1uHBH5VtvIXd9cCd0sf1qgQife9wS1iG+V/FO5o8DYFsQJzWGOrg0o7+nSNzqW9ZwDwTCF5MRU7pIFJef63qWAk0DqWHOOpylnKbkKc/E0zX08SIXMPZ03VBUnLlMeU67Jl+y8seeJhhZSEJpV9qhjaF4Jc1q7tWd3cAHPOT3AtTPEEFNXgz9ZfKRyXHHmsdjVj/y0Qt4FjS2GFDBrakKHtV9niG+8a6o/3dHO/5kpYWfOizHXlP4c75QMXmvbpPmKum2w0zLGI4dlru8SymB0h39SxixsYH+wubPCfL4nPqf0gewyPX18MgBd8PmUNjv16J9c4uVK+uVRm2R/W5n7RgSmAGOKmv7BwDKwwEH0pLaMWkx+FKsphBD6C4YdFNNvdVeVwzf1wkY5CE9H/F8JpjrOTtsOh+9y23plhJTDqWjOUIbjL0rb5+D0JZmrXUxohfXZjhkHaHTcL+dA2IUhn2WUJ5qx6jIn4TPeBXTaNMhfHWAjVCZo0TNxXpDJRXFmRiF4cOjIwKob5BzoE+wWddQmNZCjVz56Sk=
  skip_cleanup: true
  on:
    tags: true
  skip_existing: true

